package com.convx.desktop.spikes

import org.jetbrains.skia.Data
import org.jetbrains.skia.RuntimeEffect
import org.jetbrains.skia.Shader
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.nio.ByteBuffer
import java.nio.ByteOrder

class SpikeS1GlassShaderTest {

    private val roundedRectSDF = """
        float radiusAt(float2 coord, float4 radii) {
            if (coord.x >= 0.0) {
                if (coord.y <= 0.0) return radii.y;
                else return radii.z;
            } else {
                if (coord.y <= 0.0) return radii.x;
                else return radii.w;
            }
        }

        float sdRoundedRect(float2 coord, float2 halfSize, float radius) {
            float2 cornerCoord = abs(coord) - (halfSize - float2(radius));
            float outside = length(max(cornerCoord, 0.0)) - radius;
            float inside = min(max(cornerCoord.x, cornerCoord.y), 0.0);
            return outside + inside;
        }

        float2 gradSdRoundedRect(float2 coord, float2 halfSize, float radius) {
            float2 cornerCoord = abs(coord) - (halfSize - float2(radius));
            if (cornerCoord.x >= 0.0 || cornerCoord.y >= 0.0) {
                return sign(coord) * normalize(max(cornerCoord, 0.0));
            } else {
                float gradX = step(cornerCoord.y, cornerCoord.x);
                return sign(coord) * float2(gradX, 1.0 - gradX);
            }
        }
    """.trimIndent()

    private val roundedRectRefractionShaderString = """
        uniform shader content;

        uniform float2 size;
        uniform float2 offset;
        uniform float4 cornerRadii;
        uniform float refractionHeight;
        uniform float refractionAmount;
        uniform float depthEffect;

        $roundedRectSDF

        float circleMap(float x) {
            return 1.0 - sqrt(1.0 - x * x);
        }

        half4 main(float2 coord) {
            float2 halfSize = size * 0.5;
            float2 centeredCoord = (coord + offset) - halfSize;
            float radius = radiusAt(coord, cornerRadii);
            
            float sd = sdRoundedRect(centeredCoord, halfSize, radius);
            if (-sd >= refractionHeight) {
                return content.eval(coord);
            }
            sd = min(sd, 0.0);
            
            float d = circleMap(1.0 - -sd / refractionHeight) * refractionAmount;
            float gradRadius = min(radius * 1.5, min(halfSize.x, halfSize.y));
            float2 grad = normalize(gradSdRoundedRect(centeredCoord, halfSize, gradRadius) + depthEffect * normalize(centeredCoord));
            
            float2 refractedCoord = coord + d * grad;
            return content.eval(refractedCoord);
        }
    """.trimIndent()

    @Test
    fun testSkiaCompilesRefractionShader() {
        println("=== SPIKE S1: COMPILING CONVX AGSL SHADER IN SKIA SKSL ===")
        val runtimeEffect = RuntimeEffect.makeForShader(roundedRectRefractionShaderString)
        assertNotNull("Skia RuntimeEffect should compile without errors", runtimeEffect)
        println("SUCCESS: Skia RuntimeEffect compiled successfully!")

        // Test uniform binding
        // Uniform layout:
        // size: float2 (8 bytes)
        // offset: float2 (8 bytes)
        // cornerRadii: float4 (16 bytes)
        // refractionHeight: float (4 bytes)
        // refractionAmount: float (4 bytes)
        // depthEffect: float (4 bytes)
        // Total uniform bytes = 44 bytes
        val buffer = ByteBuffer.allocate(64).order(ByteOrder.LITTLE_ENDIAN)
        buffer.putFloat(200f) // size.x
        buffer.putFloat(60f)  // size.y
        buffer.putFloat(0f)   // offset.x
        buffer.putFloat(0f)   // offset.y
        buffer.putFloat(30f)  // cornerRadii.x
        buffer.putFloat(30f)  // cornerRadii.y
        buffer.putFloat(30f)  // cornerRadii.z
        buffer.putFloat(30f)  // cornerRadii.w
        buffer.putFloat(19.2f) // refractionHeight (0.4 * 48)
        buffer.putFloat(-28.8f) // refractionAmount (-0.6 * 48)
        buffer.putFloat(0f)    // depthEffect

        val uniformData = Data.makeFromBytes(buffer.array(), 0, 44)
        val dummyShader = Shader.makeColor(0xFF1A1A1A.toInt())
        val children = arrayOf<Shader?>(dummyShader)

        val appliedShader = runtimeEffect.makeShader(uniformData, children, null)
        assertNotNull("appliedShader should be generated by Skia RuntimeEffect", appliedShader)
        println("SUCCESS: Uniform buffer (44 bytes) bound and Skia Shader evaluated successfully!")
        assertTrue("Shader instance is active", !appliedShader.isClosed)
    }
}
